typography_spectrum: 0.8945895
color:
  saturation: 0.7924441
  lightness: 0.5046642
  brandStrength: 0.3633238
  rhythmicContrast: 0.6268657
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.6077425
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7225cf76-95c8-4469-9033-4864997fdb15.jpg
name: Shootnstars
title: Action Capture
description: We stop time so you can enjoy them
